<?php

/**
 * Copyright (c) 2025 Fexa AI
 *
 * All Rights Reserved.
 *
 * This module is proprietary software owned by Fexa AI.
 */

namespace PrestaShop\Module\FexaAiConnector\Mcp\Tools;

if (!defined('_PS_VERSION_')) {
    exit;
}

use Configuration;

/**
 * Store + serve the shop's /llms.txt (machine-readable AEO map for AI answer
 * engines). The markdown is generated by the SaaS and stored here. This lite
 * (PHP 7.4) build keeps it in PrestaShop Configuration (no custom table) — the
 * `llms` front controller serves it at the domain root.
 *
 * Purely additive: writes only its own Configuration key, never touches catalogue
 * data, and is multishop-aware (per-shop value with a global fallback).
 */
class LlmsTxtTools
{
    const KEY = 'FEXA_AI_LLMS_TXT';
    // Configuration.value is a TEXT column (~65535 bytes); stay safely under it.
    const MAX_BYTES = 60000;

    public function setLlmsTxt(string $content, ?int $id_shop = 0, ?int $id_lang = 0): array
    {
        $content = trim($content);

        if ($content === '') {
            throw new \Exception('content is empty');
        }
        if (strlen($content) > self::MAX_BYTES) {
            throw new \Exception('content too large');
        }
        // Must look like an llms.txt: at least one markdown H1. We never serve
        // arbitrary content at the domain root.
        if (!preg_match('/^#\s+/m', $content)) {
            throw new \Exception('content must contain a markdown H1 (a line starting with "# ")');
        }

        $idShop = ((int) $id_shop) ?: null; // null = global (all shops)
        // $html = true so the markdown (#, [], (), …) is stored verbatim, not stripped.
        Configuration::updateValue(self::KEY, $content, true, null, $idShop);

        return array('status' => 'success', 'id_shop' => (int) $id_shop, 'bytes' => strlen($content));
    }

    public function getLlmsTxt(?int $id_shop = 0, ?int $id_lang = 0): array
    {
        $idShop = ((int) $id_shop) ?: null;
        $content = Configuration::get(self::KEY, null, null, $idShop);

        return array(
            'id_shop' => (int) $id_shop,
            'content' => ($content !== false && $content !== null) ? (string) $content : null,
        );
    }

    public function deleteLlmsTxt(?int $id_shop = 0, ?int $id_lang = 0): array
    {
        $idShop = ((int) $id_shop) ?: null;
        // Empty value → the front controller returns 404.
        Configuration::updateValue(self::KEY, '', true, null, $idShop);

        return array('status' => 'deleted', 'id_shop' => (int) $id_shop);
    }
}
